# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"

    wget $CHROMEDRIVER_URL -O chromedriver_linux64.zip
    unzip chromedriver_linux64.zip

    sudo mv chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver

    CHROMEDRIVER_VERSION=$(chromedriver --version)
    echo "Versión de ChromeDriver instalada: $CHROMEDRIVER_VERSION"
  displayName: 'Instalar ChromeDriver'


- script: |
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list

    sudo apt-get update
    sudo apt-get install google-chrome-stable

    CHROME_VERSION=$(google-chrome --version)
    echo "Versión de Google Chrome instalada: $CHROME_VERSION"
  displayName: 'Instalar Google Chrome'