trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:

      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python
      
      - script: |
          branchName=$(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')
          echo "##vso[task.setvariable variable=branchName]$branchName"
        displayName: Eliminar prefijo "refs/heads/"

      - script: |
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.Repository.Name)"
          git checkout $(branchName)
          git branch
          git add envoy.yaml
          git commit -m "Actualizar archivo envoy.yaml"
          git push origin --force-with-lease --set-upstream
        displayName: Actualizar archivo en repositorio
