trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:
      
      # - task: UsePythonVersion@0
      #   inputs:
      #     versionSpec: '3.x'
      #     addToPath: true
      #     architecture: 'x64'

      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(System.DefaultWorkingDirectory)/text-manipulation.py'