trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:

      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python

      - script: |
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.Repository.Name)"
          git checkout $(Build.SourceBranch)
          git add envoy.yaml
          git commit -m "Actualizar archivo envoy.yaml"
          git push origin HEAD $(Build.SourceBranch) --force-with-lease --set-upstream
        displayName: Actualizar archivo en repositorio
