trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        vmImage: 'ubuntu-20.04'

      steps:
      - checkout: self
        fetchDepth: 0

      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python text manipulation

      - script: |
            git config --global user.email "$(Build.RequestedForEmail)"
            git config --global user.name "$(Build.Repository.Name)"
            git remote -v
            git checkout -b feature/repo origin/feature/repo
            git branch -a
            echo "hola" >> archivo.txt
            git add .
            git commit -m "update"
            git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin feature/re
        displayName: Actualizar repositorio
