
trigger: none

parameters:

- name: selectAks
  displayName: Select Aks, but ignore in case of Oks.
  type: string
  default: aks
  values:
  - aks
  - aks2

- name: stage
  displayName: stage
  type: string
  default: dev
  values:
  - dev
  - qa
  - pdn
  
pool:
  name: agent-Alejo

steps:

- script: |
    if [ "${{ parameters.selectAks }}" == "aks2" ]; then
      file_path="envoy-aks2-${{ parameters.stage }}.yaml"
    else
      file_path="envoy-${{ parameters.stage }}.yaml"
    fi
    echo $file_path
  displayName: 'echo $file_path'

- task: PythonScript@0
  displayName: 'Create and add envoy new blocks'
  inputs:
    scriptSource: 'inline'
    script: |

      if "${{ parameters.selectAks }}" == "aks2":
        file_path = "envoy-aks2-${{ parameters.stage }}.yaml"
      else:
        file_path = "envoy-${{parameters.stage}}.yaml"
      
      print(file_path)