trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: ubuntu-20.04

      steps:
      - checkout: self

      - script: |
            git remote -v
            git branch -a

      # - script: |
      #     git config --global user.email "$(Build.RequestedForEmail)"
      #     git config --global user.name "$(Build.Repository.Name)"
      #     git config --global http.extraheader "Authorization: Bearer $(System.AccessToken)"
      #     git clone $(Build.Repository.Uri) --branch $(Build.SourceBranchName)
      #     git remote -v
      #     git checkout -b master origin/master
      #     git branch -a
      #     ls
      #   displayName: Clonar el repositorio

      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python text manipulation

      - script: |
          git branch -a
        displayName: Run python text manipulation
