# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sleep 2m
  displayName: '2 minutes'
  timeoutInMinutes: 1
  continueOnError: true
  # retryCountOnTaskFailure: 3

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  displayName: Test on the Android Emulator
  inputs:
    targetType: inline
    script: |
      #!/bin/bash

      # Ejecutar la instrucción (en este caso, sleep 2m) con un límite de tiempo de 1 minuto (60 segundos)
      timeout 60s sleep 2m

      # Comprobar el código de salida del comando
      if [ $? -eq 124 ]; then
        # El comando excedió el tiempo límite
        echo "La instrucción excedió el tiempo límite de 1 minuto."
        exit 1
      fi

      # Si la instrucción se completó dentro del límite de tiempo
      echo "La instrucción se completó en menos de 1 minuto."
  retryCountOnTaskFailure: 3

- script: echo Hello, world!
  displayName: 'Run a one-line script'