trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:
      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python text manipulation

      - script: |
          echo "Clonando el repositorio..."
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.Repository.Name)"
          git clone $(Build.Repository.Uri)
          git checkout $(Build.SourceBranchName)
          echo "Conexión exitosa al repositorio"
        env:
          System.AccessToken: $(System.AccessToken)
        displayName: Actualizar archivo en repositorio

      # - script: |
      #     git config --global user.email "ssreshta@xyz.com" 
      #     git config --global user.name "ssreshta" 
      #     git add .
      #     git commit -m "update SP_BuildOrder JSON file again" 
      #     git status 
      #     git push -u https://ssreshta:mypassword@bitbucket.org/xyz/abcd.git HEAD:feature/2020q2
      #   displayName: Actualizar archivo en repositorio