trigger: none

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:
      - checkout: none
      
      - script: |
          pip install pyyaml
        displayName: Pip install request python modules
      
      - script: |
          python3 text-manipulation.py
        displayName: Run python text manipulation




      # - script: |
      #     git checkout $(Build.SourceBranchName)
      #     git add envoy.yaml
      #     git commit -m "Update envoy.yaml"
      #     git push
      #   displayName: 'Actualizar archivo en repositorio'

      # - script: |
      #     git config --global user.email "$(Build.RequestedForEmail)"
      #     git config --global user.name "$(Build.Repository.Name)"
      #     git config --global http.extraheader "Authorization: Bearer $(System.AccessToken)"
      #     git clone $(Build.Repository.Uri) --branch $(Build.SourceBranchName)
      #     git branch -a
      #   displayName: Clonar el repositorio
