trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '19')]
    #     JAVA_HOME_18_X64: '/usr/lib/jvm/jdk-19'
    #     JAVA_HOME_21_X64: '/usr/lib/jvm/jdk-21-oracle-x64'

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        sudo apt-get install openjdk-19-jdk

    - script: |
        java -version
        echo $JAVA_HOME
        echo $PATH

    - script: |
        sudo update-alternatives --display java


