trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '19')]

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        mkdir external_java
        cd external_java
        wget https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.tar.gz 
        mkdir java_19
        ls
    
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'LocalDirectory'
        jdkFile: '$(System.DefaultWorkingDirectory)/external_java/java_19/jdk-19.0.2_linux-x64_bin.tar.gz '
        jdkDestinationDirectory: "/builds/binaries/externals"
        cleanDestinationDirectory: true

    - script: |
        java -version



