trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '19')]

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        sudo apt-get install openjdk-$(versionSpecification)-jdk
    
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # - task: JavaToolInstaller@0
    #   displayName: 'Use Java $(versionSpecification)'
    #   inputs:
    #     versionSpec: '$(versionSpecification)'
    #     jdkArchitectureOption: 'x64'
    #     jdkSourceOption: 'PreInstalled'

    - script: |
        java -version



