trigger: none
pool:
  name: 'Azure Pipelines'
stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    steps:

    - task: GoTool@0
      inputs:
        version: '1.13.5'

    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)/greeter'

    # - task: SonarQubePrepare@5
    #   inputs:
    #     SonarQube: 'Sonarqube-flutter'
    #     scannerMode: 'CLI'
    #     configMode: 'manual'
    #     cliProjectKey: 'test-Alejandro'

    # - task: SonarQubeAnalyze@5

    # - task: SonarQubePublish@5
    #   inputs:
    #     pollingTimeoutSec: '300'}

    - task: SonarCloudPrepare@1
      displayName: 'SonarCloud Prepare'
      inputs:
        SonarCloud: 'sonar-loida'
        organization: 'quind'
        scannerMode: "Other"
        extraProperties: |
          sonar.projectKey=test-Alejandro
          sonar.projectName=test-Alejandro

    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/greeter'
  
    - task: SonarCloudPublish@1
      displayName: 'SonarCloud Publish'
      inputs:
        pollingTimeoutSec: '300'

    - task: sonarcloud-buildbreaker@2
      displayName: 'SonarCloud Quality gate'
      inputs:
        SonarCloud: 'sonar-loida'
        organization: 'quind'
# - script: tree

    - task: CopyFiles@2
      displayName: Copy files
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/greeter'
        Contents: 'greeter'
        flattenFolders: true 
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: drop

