trigger: none

variables:
  - group: alejo-var-infra

  - name: sshPub
    value: $(sshPub.secureFilePath)

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: DownloadSecureFile@1
      displayName: 'VM ssh file download'
      name: sshPub
      inputs:
        secureFile: 'alejo-ssh.pub'

    - task: replacetokens@3
      displayName: 'Replace Tokens for bash scripts'
      inputs:
        targetFiles: |
          scripts/*.sh

    - task: Bash@3
      inputs:
        filePath: 'scripts/az-infra.sh'
    
    - task: replacetokens@3
      displayName: 'Replace Tokens for terraform scripts'
      inputs:
        targetFiles: |
          terraform/*.tf

    - task: TerraformInstaller@1
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
    
    - script: |
        terraform init
      displayName: 'terraform init'
      workingDirectory: 'terraform/'

    - script: |
        terraform plan
      displayName: 'terraform plan'
      workingDirectory: 'terraform/'

    - script: |
        terraform apply -auto-approve
      displayName: 'terraform apply'
      workingDirectory: 'terraform/'

    - script: |
        az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
        az vm list --output table --resource-group $(RESOURCE_GROUP)
