trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        echo $(var_test1)
      displayName: 'echo script'
    #   timeoutInMinutes: 1
    #   continueOnError: true
    #   retryCountOnTaskFailure: 3