parameters:

- name: installOks
  displayName: 'Install Front on OKS'
  type: boolean

- name: installAks
  displayName: 'Install Front on AKS'
  type: boolean

jobs:
- template: Test/main-test.yml
  parameters:
    branchOptions: 
      - ${{ parameters.installOks }}
      - ${{ parameters.installAks }}

