trigger: none

parameters:
- name: javaVersion
  displayName: 'javaVersion'
  type: string
  default: ''

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: ${{parameters.javaVersion}}

    pool:
      vmImage: ubuntu-22.04

    steps:
    - script: | 
        echo "su versión: $(versionSpecification)"

        if [[ "$(versionSpecification)" != @("8"|"11"|"17"|"21") ]]; then
            version=$(versionSpecification)

            case $version in
                9)
                    url="https://download.java.net/java/GA/jdk9/9/binaries/openjdk-9_linux-x64_bin.tar.gz"
                    ;;
                10)
                    url="https://download.java.net/java/GA/jdk10/10/binaries/openjdk-10_linux-x64_bin.tar.gz"
                    ;;
                12)
                    url="https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_linux-x64_bin.tar.gz"
                    ;;
                13)
                    url="https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz"
                    ;;
                14)
                    url="https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_linux-x64_bin.tar.gz"
                    ;;
                15)
                    url="https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz"
                    ;;
                16)
                    url="https://download.java.net/java/GA/jdk16/7863447f0ab643c585b9bdebf67c69db/36/GPL/openjdk-16_linux-x64_bin.tar.gz"
                    ;;
                18)
                    url="https://download.java.net/java/GA/jdk18/43f95e8614114aeaa8e8a5fcf20a682d/36/GPL/openjdk-18_linux-x64_bin.tar.gz"
                    ;;
                19)
                    url="https://download.java.net/java/GA/jdk19/877d6127e982470ba2a7faa31cc93d04/36/GPL/openjdk-19_linux-x64_bin.tar.gz"
                    ;;
                20)
                    url="https://download.java.net/java/GA/jdk20/bdc68b4b9cbc4ebcb30745c85038d91d/36/GPL/openjdk-20_linux-x64_bin.tar.gz"
                    ;;
                *)
                    echo "Versión no soportada: $version"
                    exit 1
                    ;;
            esac

            # Descargar el archivo tar.gz
            wget "$url"

            # Tu lógica adicional aquí, por ejemplo, descomprimir el archivo
            tar -zxvf openjdk-$(versionSpecification)_linux-x64_bin.tar.gz -C /usr/lib/jvm
            ls /usr/lib/jvm/
            echo "##vso[task.setvariable variable=JAVA_HOME_$(versionSpecification)_X64]/usr/lib/jvm/jdk-$(versionSpecification)"
            echo "Descargado e instalado Java $version"
        else
             echo "La versión actual de Java $version esta preinstalada en el agente."
        fi
      displayName: 'Validate specific version'

    - task: JavaToolInstaller@0
      displayName: 'Use Java $(versionSpecification)'
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        java -version



