trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '12')]

    pool:
      vmImage: ubuntu-22.04

    steps:

    - script: |
      sudo add-apt-repository ppa:openjdk/java-12-ppa
      sudo apt update
      sudo apt install openjdk-12-jdk

    # - script: | 
    #     echo "su versión: $(versionSpecification)"
    #     if [[ "$(versionSpecification)" != @("8"|"11"|"17"|"21") ]]; 
    #     then
    #       sudo apt install openjdk-12-jdk-headless
    #       echo "##vso[task.setvariable variable=JAVA_HOME_$(versionSpecification)_X64]/usr/lib/jvm/java-$(versionSpecification)-openjdk-amd64"
    #     fi
    #   displayName: 'Validate specific version'

    - task: JavaToolInstaller@0
      displayName: 'Use Java $(versionSpecification)'
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: |
        java -version



