trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: macOS-12

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        brew install oci-cli

        mkdir $(System.DefaultWorkingDirectory)/.oci
        echo -e "[DEFAULT]
        tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaa625xcguiizsahhzszll5yf43hgmtruxmpakup5vwckyvjhxvvfqq
        user_ocid = ocid1.user.oc1..aaaaaaaasxttbjc5bi7rvj6eric7hmta4que7lxohnxlokqudixrnh2llkga
        fingerprint = 5a:3d:a5:e1:c0:10:f1:b6:a1:a8:c8:3f:f2:98:88:3a
        private_key_path = $(System.DefaultWorkingDirectory)/private_general_oci_connection.pem
        region = sa-bogota-1" > $(System.DefaultWorkingDirectory)/.oci/config

        cat $(System.DefaultWorkingDirectory)/.oci/config

        oci --version

        oci compute instance list --compartment-id ocid1.compartment.oc1..aaaaaaaadhms2usmx5p2cozhd6axyv2pbowhop5ap46c3ts62d44jrliid3a
      displayName: 'oci cli install script'

    - script: |
        echo hola
      displayName: 'oci cli connect'
