trigger: none

parameters:

- name: installOks
  displayName: 'Install Front on OKS'
  type: boolean

- name: installAks
  displayName: 'Install Front on AKS'
  type: boolean

- name: installAks2
  displayName: 'Install on AKS 2'
  type: boolean

- name: installOke
  displayName: 'Install on OKE'
  type: boolean


- name: myStep
  type: step
  default:
    script: echo my step

variables:
- name: installCluster
  value: |
    - True
    - OKS: ${{ parameters.installOks }}
    - AKS: ${{ parameters.installAks }}
    - AKS2: ${{ parameters.installAks2 }}
    - OKE: ${{ parameters.installOke }}
    - True
    - b: True

jobs:
# - template: Test/main-test.yml
#   parameters:
#     branchOptions: 
#       - ${{ parameters.installOks }}
#       - ${{ parameters.installAks }}

- job: A1 
  steps:
  - ${{ each value in containsValue( split(variables.installCluster, '-'), 'True' ) }}:
    - ${{ if ne(value, '') }}:
      - script: echo ${{ value }}

  - ${{ parameters.myStep }}