trigger: none
pool:
  name: 'myagent-agenteloi'
stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    steps:

    - task: GoTool@0
      inputs:
        version: '1.13.5'

    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)/greeter'

    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'Sonarqube-flutter'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'test-Alejandro'

    - task: SonarQubeAnalyze@5

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/greeter'
    
   # - script: tree

    - task: CopyFiles@2
      displayName: Copy files
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/greeter'
        Contents: 'greeter'
        flattenFolders: true 
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: drop

