trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: macOS-12

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        brew install oci-cli
      displayName: 'oci cli install script'

    - script: |
        export OCI_CLI_TENANCY_OCID=ocid1.tenancy.oc1..aaaaaaaa625xcguiizsahhzszll5yf43hgmtruxmpakup5vwckyvjhxvvfqq
        export OCI_CLI_USER_OCID=ocid1.user.oc1..aaaaaaaasxttbjc5bi7rvj6eric7hmta4que7lxohnxlokqudixrnh2llkga
        export OCI_CLI_FINGERPRINT=5a:3d:a5:e1:c0:10:f1:b6:a1:a8:c8:3f:f2:98:88:3a
        export OCI_CLI_PRIVATE_KEY_PATH=$(System.DefaultWorkingDirectory)/private_general_oci_connection.pem
        export OCI_CLI_REGION=sa-bogota-1

        oci --version

        oci compute instance list --compartment-id ocid1.compartment.oc1..aaaaaaaa6ijlvgsvu7emtoyt764nvh7ozsc6t67sy2z6gue427f57g4o2neq
      displayName: 'oci cli connect'
