trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: macOS-12

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        brew install oci-cli
      displayName: 'oci cli install script'

    - script: |
        export OCI_CLI_TENANCY_OCID=ocid1.tenancy.oc1..aaaaaaaa625xcguiizsahhzszll5yf43hgmtruxmpakup5vwckyvjhxvvfqq
        export OCI_CLI_USER_OCID=ocid1.user.oc1..aaaaaaaasxttbjc5bi7rvj6eric7hmta4que7lxohnxlokqudixrnh2llkga
        export OCI_CLI_FINGERPRINT=3b:20:6d:0b:f0:a5:d1:55:03:5d:ed:1c:da:16:b3:6f
        export OCI_CLI_PRIVATE_KEY_PATH=$(System.DefaultWorkingDirectory)/OCI-private-key.pem
        export OCI_CLI_REGION=sa-bogota-1

        oci --version
        oci setup autocomplete

        # oci compute instance list --compartment-id ocid1.compartment.oc1..aaaaaaaadhms2usmx5p2cozhd6axyv2pbowhop5ap46c3ts62d44jrliid3a
      displayName: 'oci cli connect'
