trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-20.04

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        wget https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        chmod +x install.sh
        sudo ./install.sh --accept-all-defaults --exec-dir $(System.DefaultWorkingDirectory)/oci-cli --install-dir $(System.DefaultWorkingDirectory)/oci-cli --script-dir $(System.DefaultWorkingDirectory)/oci-cli 
      displayName: 'oci cli connect'

    - script: |
        $(System.DefaultWorkingDirectory)/oci-cli/oci --help
        $(System.DefaultWorkingDirectory)/oci-cli/oci --version
        tree
        #$(System.DefaultWorkingDirectory)/oci-cli/oci compute instance list --compartment-id ocid1.compartment.oc1..aaaaaaaa6ijlvgsvu7emtoyt764nvh7ozsc6t67sy2z6gue427f57g4o2neq
      displayName: 'oci cli connect'
