trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Go@0
      inputs:
        command: 'build'
    
    - script: tree