trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-20.04

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        wget https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        chmod +x install.sh
        ./install.sh --accept-all-defaults
      displayName: 'oci cli connect'

    - script: |
        echo hola
      displayName: 'oci cli connect'
