trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-20.04

    steps:

    - task: TerraformInstaller@0
      displayName: 'Install or Update Terraform'
      inputs:
        terraformVersion: 1.0.7
              
    - script: |
        wget https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
        chmod +x install.sh
        sudo ./install.sh --accept-all-defaults --exec-dir $(System.DefaultWorkingDirectory)/oci-cli --install-dir $(System.DefaultWorkingDirectory)/oci-cli --script-dir $(System.DefaultWorkingDirectory)/oci-cli 
      displayName: 'oci cli connect'

    - script: |
        $(System.DefaultWorkingDirectory)/oci-cli/oci --version
        $(System.DefaultWorkingDirectory)/oci-cli/oci compute instance list --compartment-id ocid1.compartment.oc1..aaaaaaaa6ijlvgsvu7emtoyt764nvh7ozsc6t67sy2z6gue427f57g4o2neq
      displayName: 'oci cli connect'
      env:
        OCI_CLI_TENANCY: ocid1.tenancy.oc1..aaaaaaaa625xcguiizsahhzszll5yf43hgmtruxmpakup5vwckyvjhxvvfqq
        OCI_CLI_USER: ocid1.user.oc1..aaaaaaaasxttbjc5bi7rvj6eric7hmta4que7lxohnxlokqudixrnh2llkga
        OCI_CLI_FINGERPRINT: 5a:3d:a5:e1:c0:10:f1:b6:a1:a8:c8:3f:f2:98:88:3a
        OCI_CLI_KEY_FILE: $(System.DefaultWorkingDirectory)/private_general_oci_connection.pem
        OCI_CLI_REGION: sa-bogota-1
        OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING: True
