parameters:
- name: branchOptions
  displayName: Source branch options
  type: object
  default:
    - refs/heads/main
    - refs/heads/test

variables:
- name: myVariable
  value: ${{ parameters.branchOptions }}

jobs:
  - job: A1 
    steps:
    - ${{ each value in variables.myVariable }}:
      - script: echo ${{ value }}
