trigger: none

parameters:

- name: installOks
  displayName: 'Install on OKS'
  type: boolean

- name: installAks
  displayName: 'Install on AKS'
  type: boolean

- name: installAks2
  displayName: 'Install on AKS 2'
  type: boolean

- name: installOke
  displayName: 'Install on OKE'
  type: boolean

- name: branch
  displayName: 'Branch Prefix'
  type: string
  default: dev
  values:
  - dev
  - qa
  # - pdn

- name: createNamespace
  displayName: 'Namespace'
  type: string
  default: none
  values:
  - upgrade
  - delete
  - none

- name: helmOperator
  displayName: 'Operator Helm command'
  type: string
  default: none
  values:
  - upgrade
  - delete
  - none

- name: helmCollector
  displayName: 'Collector Helm command'
  type: string
  default: none
  values:
  - upgrade
  - delete
  - none

- name: helmInstrumentation
  displayName: 'Instrumentation Kube command'
  type: string
  default: none
  values:
  - upgrade
  - delete
  - none

variables:
- name: installCluster
  value: |
    - OKS_${{ parameters.installOks }}
    - AKS_${{ parameters.installAks }}
    - AKS2_${{ parameters.installAks2 }}
    - OKE_${{ parameters.installOke }}

- branch: ${{ parameters.branch }}

jobs:
# - template: Test/main-test.yml
#   parameters:
#     branchOptions: 
#       - ${{ parameters.installOks }}
#       - ${{ parameters.installAks }}

- job: A1 
  steps:
  - ${{ each value in split(variables.installCluster, '-')}}:
    - ${{ if and(contains(value, 'True'), ne(value, '') ) }}:
      - script: echo ${{ value }}
  
  - script: echo $(branch)