trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '19')]

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        sudo apt-get install openjdk-$(versionSpecification)-jdk
        java_19_path=$(update-alternatives --list java | grep "java-19")
        echo "La ruta de Java 19 es: $java_19_path"
        echo "##vso[task.setvariable variable=java_19_path]$java_19_path"
    
    - script: echo $(java_19_path)
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'LocalDirectory'
        jdkFile: '$(java_19_path)'
        jdkDestinationDirectory: "/builds/binaries/externals"
        cleanDestinationDirectory: true

    - script: |
        java -version



