trigger: none

variables:
- group: Alejo-test-sonar
- group: alejo-var-back

- name: sonarTest
  value: sonar.verbose=false ; sonar.c.file.suffixes=- ; sonar.cpp.file.suffixes=- ; sonar.objc.file.suffixes=-


stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: git://training-quind/training-AlejandroFront@master
      fetchDepth: 1

    - task: SonarCloudPrepare@1
      displayName: 'Configure Static Code Analysis'
      inputs:
        SonarCloud: 'sonarcloud-Alejandro'
        organization: 'quind'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(Build.Repository.Name)'
        cliProjectName: '$(Build.Repository.Name)'
        cliSources: '$(System.DefaultWorkingDirectory)'
        extraProperties: |
          sonar.exclusions= **/node_modules/**,**/*.test.js,**/alejo-helm/**
          sonar.testExecutionReportPaths=test-report.xml
          sonar.javascript.lcov.reportPaths=coverage/lcov.info

    - task: Npm@1
      displayName: 'Install Dependencies'
      inputs:
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: true
    
    - task: Npm@1
      displayName: 'jest sonar reporter'
      inputs:
        command: 'custom'
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: true
        customCommand: 'i -D jest-sonar-reporter'

    - task: Npm@1
      displayName: 'Compile'
      inputs:
        command: 'custom'
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: true
        customCommand: 'run build'
        
    - task: SonarCloudAnalyze@1
      displayName: 'Configure Static Code Analysis'

    - task: Npm@1
      displayName: 'Unit Tests'
      inputs:
        command: 'custom'
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: true
        customCommand: 'run test'
        
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
        
    # - task: JavaToolInstaller@0
    #   displayName: Install Java 17
    #   inputs:
    #     versionSpec: 17
    #     jdkArchitectureOption: x64
    #     jdkSourceOption: PreInstalled

    # - task: SonarCloudPrepare@1
    #   inputs:
    #     SonarCloud: 'sonarcloud-Alejandro'
    #     organization: 'quind'
    #     scannerMode: 'Other'
    #     extraProperties: |
    #         $(sonarPropertiesLibrary2)

    # - task: Gradle@3
    #   inputs:
    #     gradleWrapperFile: 'gradlew'
    #     tasks: 'build'
    #     publishJUnitResults: true
    #     testResultsFiles: '**/TEST-*.xml'
    #     javaHomeOption: 'JDKVersion'
    #     sonarQubeRunAnalysis: true
    #     sqGradlePluginVersionChoice: 'build'
    #     spotBugsAnalysis: false
    #     options: --stacktrace

    # - task: SonarCloudPublish@1
    #   inputs:
    #     pollingTimeoutSec: '300'
          

