parameters:
- name: installOks
  displayName: 'Install Front on OKS'
  type: boolean

- name: installAks
  displayName: 'Install Front on AKS'
  type: boolean

variables:
- name: test
  value: 
    - ${{ parameters.installOks }}
    - ${{ parameters.installAks }}

jobs:
  - job: A1 
    steps:
    - ${{ each value in variables['test'] }}:
      - script: echo ${{ value }}
