trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'

    variables:
        versionSpecification: $[coalesce(variables.javaVersion, '19')]
        # JAVA_HOME_19_X64: '/usr/lib/jvm/java-19-openjdk-amd64'

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: |
        sudo apt-get install openjdk-19-jdk
        echo "##vso[task.setvariable variable=JAVA_HOME_19_X64]/usr/lib/jvm/java-19-openjdk-amd64"

    - script: |
        java -version

    - script: |
        sudo update-alternatives --display java

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(versionSpecification)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        java -version



