trigger: none


stages:
- stage: stage
  displayName: stage
  jobs:
  - deployment: job
    displayName: 'job'
    environment: Alejo-prueba
    strategy:
        runOnce:
            deploy:
                steps:

                - script: echo hola
