parameters:
- name: branchOptions
  displayName: Source branch options
  type: object
  default:
    - refs/heads/main
    - refs/heads/test

variables:
- name: myVariable
  value: ${{ parameters.branchOptions }}

jobs:
- template: Test/main-test.yml
  parameters:
    language: ${{ parameters.language }}
    build: ${{ parameters.build }}
    typerelease: ${{ parameters.typerelease }}
