trigger: none

parameters:

- name: installOks
  displayName: 'Install Front on OKS'
  type: boolean

- name: installAks
  displayName: 'Install Front on AKS'
  type: boolean

- name: myStep
  type: step
  default:
    script: echo my step

variables:
- name: installCluster
  value: |
    ${{ parameters.installOks }}
    , ${{ parameters.installAks }}

jobs:
# - template: Test/main-test.yml
#   parameters:
#     branchOptions: 
#       - ${{ parameters.installOks }}
#       - ${{ parameters.installAks }}

- job: A1 
  steps:
  - ${{ each value in split(variables.installCluster, ',')}}:
    - script: echo ${{ value }}

  - ${{ parameters.myStep }}