trigger: none

# parameters:
# - name: parameter
#   displayName: parameter
#   type: string
#   default: default

variables:
- name: organization
  value: quind

- name: project
  value: training-quind

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        vmImage: 'ubuntu-20.04'

      steps:

      - script: |
          curl -u $(organization)[:$(System.AccessToken)] https://dev.azure.com/$(organization)/$(project)/_apis/pipelines?api-version=6.0
