trigger: none

# parameters:
# - name: parameter
#   displayName: parameter
#   type: string
#   default: default

variables:
- name: organization
  value: quind

- name: project
  value: training-quind

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        vmImage: 'ubuntu-20.04'

      steps:

      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: |
            import requests
            
            url = "https://dev.azure.com/quind/training-quind/_apis/git/repositories?api-version=6.0"
            
            payload = {}
            headers = {
              'Authorization': 'Basic bWFudWVsLm1lbmFAcXVpbmQuaW86dmZiaG9ha3V1NXJsb2Y0ZHlpYzd2ZHZpZmk1aTd1cTd1NmFqaG9yc29ydnZkbzQ3b2lpcQ=='}
            
            response = requests.request("GET", url, headers=headers, data=payload)
            
            print(response.text)