# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: windows-2019

    steps:
    - powershell: |
          $RutaOriginal = $env:System_DefaultWorkingDirectory
          $RutaActualizada = $RutaOriginal -replace '\\', '\\\\'
          [Environment]::SetEnvironmentVariable("PythonWorkingDirectory", $RutaActualizada, [System.EnvironmentVariableTarget]::User)
          Write-Host "PythonWorkingDirectory=$RutaActualizada"
          Write-Host "##vso[task.setvariable variable=PythonWorkingDirectory;isOutput=true]$RutaActualizada"
      name: setVar

    - powershell: |
        Write-Host $(setVar.PythonWorkingDirectory)

    - task: PythonScript@0
      displayName: Vars Test
      inputs:
        scriptSource: 'inline'
        script: |
          print(f"$(setVar.PythonWorkingDirectory)")
          path = f"$(setVar.PythonWorkingDirectory)"
          print(path)
          file = path + "\\\\test.txt"
          print(file)

    # - task: UsePythonVersion@0
    #   inputs:
    #     versionSpec: '3.x'
    #     addToPath: true
    #     architecture: 'x64'

    # - script: |
    #     pip install Lackey

    #   displayName: Pip install modules

    # - task: PythonScript@0
    #   displayName: Lackey test
    #   inputs:
    #     scriptSource: 'inline'
    #     script: |
    #       import time
    #       from lackey import *

    #       app = App(0)
    #       type("notepad")
    #       type(Key.ENTER)

    #       wait(5)

    #       type("Hola, este es un texto de ejemplo.")
    #       type(Key.CTRL + 's')
    #       wait(2)

    #       path = f"$(setVar.PythonWorkingDirectory)"
    #       file = "path\\\\test.txt"

    #       type(file)  
    #       type(Key.ENTER)

    #       wait(2)

    #       app.close()

    # # - task: PublishBuildArtifacts@1
    # #   displayName: Publish artifacts
    # #   inputs:
    # #     PathtoPublish: '$(System.DefaultWorkingDirectory)/test.txt'
    # #     ArtifactName: 'drop_$(Build.Repository.Name)'
    # #     publishLocation: 'Container'