# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

stages:
- stage: stage
  displayName: stage
  jobs:
  - job: 'job'
    pool:
      vmImage: windows-2019

    steps:

    - script: |
        #!/bin/bash

        # Obtener la ruta original desde la variable de entorno System.DefaultWorkingDirectory
        RutaOriginal="$System.DefaultWorkingDirectory"

        # Reemplazar las barras invertidas con barras invertidas duplicadas
        RutaActualizada="${RutaOriginal//\\/\\\\}"

        # Establecer la variable de entorno personalizada
        export RutaActualizada="$RutaActualizada"

        # Imprimir la variable de entorno actualizada
        echo "RutaActualizada=$RutaActualizada"

      displayName: echo NewWorkingDirectory
      
    # - task: UsePythonVersion@0
    #   inputs:
    #     versionSpec: '3.x'
    #     addToPath: true
    #     architecture: 'x64'

    # - script: |
    #     pip install Lackey
    #     pip install PyAutoGUI
    #   displayName: Pip install modules

    # - task: PythonScript@0
    #   displayName: Lackey test
    #   inputs:
    #     scriptSource: 'inline'
    #     script: |
    #       import time
    #       from lackey import *

    #       app = App(0)

    #       type("notepad")
    #       type(Key.ENTER)

    #       wait(5)

    #       type("Hola, este es un texto de ejemplo.")

    #       type(Key.CTRL + 's')
    #       wait(2)
    #       type("$(NewWorkingDirectory)/test.txt")  
    #       type(Key.ENTER)

    #       wait(2)

    #       app.close()

    # - task: PublishBuildArtifacts@1
    #   displayName: Publish artifacts
    #   inputs:
    #     PathtoPublish: '$(NewWorkingDirectory)/test.txt'
    #     ArtifactName: 'drop_$(Build.Repository.Name)'
    #     publishLocation: 'Container'