trigger: none

parameters:
- name: var
  displayName: var
  type: string
  default: default

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        vmImage: 'ubuntu-20.04'

      steps:

      - checkout: self
        fetchDepth: 0
      
      - script: echo sales force test