schedules:
- cron: '44 8 * * *'
  displayName: Daily 8:42 AM build
  branches:
   include:
     - '*'

stages:
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
