trigger:
- timer:
    interval: '0/1 * * * *'

stages: 
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:

      - script: echo Hello, world!
        displayName: 'Run a one-line script'
