trigger:
# YAML file in the release branch
schedules:
- cron: "*/1 * * * *"
  displayName: Build per minute
  branches:
    include:
    - main

stages:
- stage: stage
  displayName: stage
  jobs:
    - job: 'job'
      pool:
        name: agent-Alejo

      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
