trigger: none
pr: none

schedules:
- cron: "*/1 * * * *"
  displayName: Build per minute
  branches:
    include:
    - '*'
  always: true

parameters:
- name: resourceType
  displayName: Resource Type
  default: 'PC'
  type: string
  values:
  - 'PC'
  - 'SERVER'

- name: ipDuration
  displayName: Ip Duration (Days)
  default: '15'
  type: string
  values:
  - '15'
  - '30'
  - '45'

- name: description
  displayName: New record description
  default: ''
  type: string

- name: ip
  displayName: Record Ip
  default: ''
  type: string

name: "Running... "
appendCommitMessageToRunName: false

stages: 
- ${{ if eq(variables['Build.Reason'], 'Manual') }}:

  - stage: stage_a
    displayName: stage_a
    jobs:
      - job: 'job_a'
        pool:
          name: agent-Alejo

        steps:

        - checkout: self
          fetchDepth: 0
        
        - script: |
            $NEWBUILDNUMBER="1.0.0"  # Reemplaza esto con el número de compilación que deseas usar
            echo "##vso[task.setvariable variable=Build.DefinitionName;]$NEWBUILDNUMBER"
          displayName: 'Update Build Number'

        - script: |

            json_file="rabbitmq.json"

            existing_json="rabbitmq.json"

            description="${{parameters.resourceType}}-${{parameters.description}}-Created:$(date '+%Y/%m/%d')-Duration:${{parameters.ipDuration}}"
            ip="${{parameters.ip}}" 

            if echo "$existing_json" | jq -e ".[] | select(.ip == \"$ip/32\")" > /dev/null; then
              echo "La IP "$ip" ya existe en las listas blancas."
              exit 1
            fi

            new_record="{\"description\":\"$description\",\"ip\":\"$ip/32\",\"ports\":[],\"services\":[\"AMQPS\"]}"

            jq --argjson new_rec "$new_record" '. += [$new_rec]' "$json_file" > tmp.json && mv tmp.json "$json_file"

            nuevo_json=$(cat "$json_file")

            echo "La lista blanca ha sida agregada correctamente."

          displayName: 'Run rabbitmq whitelist script'

        - task: PublishBuildArtifacts@1
          displayName: Publish artifacts
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/rabbitmq.json'
            ArtifactName: 'drop_whitelist'
            publishLocation: 'Container'

- ${{ if eq(variables['Build.Reason'], 'Schedule') }}:

  - stage: stage_b
    displayName: stage_b
    jobs:
      - job: 'job_b'
        pool:
          name: agent-Alejo

        steps:

        - script: |
            $NEWBUILDNUMBER="1.2.0"  # Reemplaza esto con el número de compilación que deseas usar
            echo "##vso[task.setvariable variable=Build.DefinitionName;]$NEWBUILDNUMBER"
          displayName: 'Update Build Number'

        - checkout: self
          fetchDepth: 0
