trigger: none
pr: none

# schedules:
# - cron: "*/5 * * * *"
#   displayName: Build per minute
#   branches:
#     include:
#     - '*'
#   always: true

parameters:
- name: resourceType
  displayName: Resource Type
  default: 'PC'
  type: string
  values:
  - 'PC'
  - 'SERVER'

- name: ipDuration
  displayName: Ip Duration (Days)
  default: '15'
  type: string
  values:
  - '15'
  - '30'
  - '45'

- name: description
  displayName: New record description
  default: ''
  type: string

- name: ip
  displayName: Record Ip
  default: ''
  type: string

name: "Running... "
appendCommitMessageToRunName: false

stages: 
- ${{ if eq(variables['Build.Reason'], 'Manual') }}:

  - stage: stage_a
    displayName: stage_a
    jobs:
      - job: 'job_a'
        pool:
          name: agent-Alejo

        steps:

        - checkout: self
          fetchDepth: 0
        
        # - script: |
        #     json_file="rabbitmq.json"
        #     existing_json="rabbitmq.json"
            
        #     ip="${{parameters.ip}}"
            
        #     # Comprobar si resourceType es "SERVER" o "PC"
        #     if [ "${{parameters.resourceType}}" = "SERVER" ]; then
        #       description="${{parameters.resourceType}}-${{parameters.description}}-Created:$(date '+%Y/%m/%d')"
        #     else
        #       description="${{parameters.resourceType}}-${{parameters.description}}-Created:$(date '+%Y/%m/%d')-Duration:${{parameters.ipDuration}}"
        #     fi
            
        #     if echo "$existing_json" | jq -e ".[] | select(.ip == \"$ip/32\")" > /dev/null; then
        #       echo "La IP "$ip" ya existe en las listas blancas."
        #       exit 1
        #     fi

        #     new_record="{\"description\":\"$description\",\"ip\":\"$ip/32\",\"ports\":[],\"services\":[\"AMQPS\"]}"

        #     jq --argjson new_rec "$new_record" '. += [$new_rec]' "$json_file" > tmp.json && mv tmp.json "$json_file"

        #     nuevo_json=$(cat "$json_file")

        #     echo "La lista blanca ha sido agregada correctamente."
        #   displayName: 'Run rabbitmq whitelist script'


        # - task: PublishBuildArtifacts@1
        #   displayName: Publish artifacts
        #   inputs:
        #     PathtoPublish: '$(System.DefaultWorkingDirectory)/rabbitmq.json'
        #     ArtifactName: 'drop_whitelist_old'
        #     publishLocation: 'Container'
        
        - script: |
            json_file="rabbitmq.json"

            # Obtener la fecha actual
            current_date=$(date +"%Y/%m/%d")

            # Función para verificar si una IP ha caducado
            verificar_caducidad() {
              ip=$1
              description=$2

              # Verificar si la descripción comienza con "SERVER" o no contiene una IP válida
              if [[ "$description" == SERVER* || ! "$ip" ]]; then
                echo "La IP $ip es de un servidor o no es válida y no será procesada."
              else
                # Extraer la fecha de creación y la duración del campo "description"
                creation_date=$(echo $description | awk -F 'Created:' '{print $2}' | awk -F '-Duration:' '{print $1}')
                duration=$(echo $description | awk -F '-Duration:' '{print $2}')

                # Calcular la fecha de caducidad
                expiration_date=$(date -d "$creation_date + $duration days" +"%Y/%m/%d")

                # Comparar las fechas y mostrar el resultado
                if [[ "$current_date" > "$expiration_date" ]]; then
                  echo "La IP $ip ha caducado y será eliminada del archivo JSON."
                  # Eliminar la IP caducada del archivo JSON
                  jq --arg ip_to_delete "$ip" 'del(.[] | select(.ip == $ip_to_delete))' "$json_file" > tmp.json && mv tmp.json "$json_file"
                else
                  echo "La IP $ip sigue vigente hasta el $expiration_date"
                fi
              fi
            }

            # Iterar sobre cada elemento del JSON
            for row in $(jq -c '.[]' "$json_file"); do
              ip=$(echo "$row" | jq -r '.ip')
              description=$(echo "$row" | jq -r '.description')

              # Llamar a la función de verificación de caducidad
              verificar_caducidad "$ip" "$description"
            done

            # Verificar si el archivo JSON se actualiza correctamente
            if cmp -s "$json_file" tmp.json; then
              echo "El archivo JSON no se ha actualizado correctamente."
            else
              echo "Las IP caducadas han sido eliminadas del archivo JSON."
            fi

            cat $json_file
          displayName: 'Check deprecated IPs'

        - task: PublishBuildArtifacts@1
          displayName: Publish artifacts
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/rabbitmq.json'
            ArtifactName: 'drop_whitelist_new'
            publishLocation: 'Container'

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop_whitelist_new'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        
        - script: ls

- ${{ if eq(variables['Build.Reason'], 'Schedule') }}:

  - stage: stage_b
    displayName: stage_b
    jobs:
      - job: 'job_b'
        pool:
          name: agent-Alejo

        steps:

        - checkout: self
          fetchDepth: 0
