desc "Test enviroment variable"
lane :test_env do
    xcode_version = ENV["XCODE_VERSION"]
    if xcode_version
        puts "msg: " + xcode_version
        xcodes(version: xcode_version)
    else
        puts "La variable de entorno XCODE_VERSION no está definida."
    end
end
