---
- hosts: dev
  remote_user: root
  become: yes
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: quind-vm-test

    - name: Add the user 'eacastaneda'
      ansible.builtin.user:
        name: eacastaneda
        group: sudo
        password: "{{ 'eacastaneda12345' | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/authorized_keys

    - name: Add the user 'sangarces'
      ansible.builtin.user:
        name: sangarces
        group: sudo
        password:  "{{ 'sangarces12345' | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/authorized_keys

    - name: Add the user 'admarus'
      ansible.builtin.user:
        name: admarus
        group: sudo
        password: "{{ 'admarus12345' | password_hash('sha512') }}"

    - name: Add the user 'Luislx'
      ansible.builtin.user:
        name: Luislx
        group: sudo
        password: "{{ 'Luislx12345' | password_hash('sha512') }}"

    - name: Add the user 'Luisre'
      ansible.builtin.user:
        name: Luisre
        group: sudo
        password: "{{ 'Luisre12345' | password_hash('sha512') }}"

    - name: Stop and disable firewall.
      service:
        name: ufw
        state: stopped
        enabled: False

    - name: Update repositories 
      ansible.builtin.apt:
        update_cache: yes
        upgrade: "dist"

    - name: Enable SELinux
      ansible.posix.selinux:
        policy: targeted
        state: enforcing