---
- hosts: dev
  remote_user: root
  become: yes
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: quind-vm-test

    - name: Add the user 'eacastaneda'
      ansible.builtin.user:
        name: eacastaneda
        group: admin
        password: "{{ lookup('pipe', 'echo -n eacastaneda12345 | mkpasswd --method=sha-512 --stdin') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/authorized_keys

    - name: Add the user 'sangarces'
      ansible.builtin.user:
        name: sangarces
        group: admin
        password: "{{ lookup('pipe', 'echo -n sangarces12345 | mkpasswd --method=sha-512 --stdin') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/authorized_keys

    - name: Add the user 'admarus'
      ansible.builtin.user:
        name: admarus
        group: admin
        password: "{{ lookup('pipe', 'echo -n admarus12345 | mkpasswd --method=sha-512 --stdin') }}"

    - name: Add the user 'Luislx'
      ansible.builtin.user:
        name: Luislx
        group: admin
        password: "{{ lookup('pipe', 'echo -n Luislx12345 | mkpasswd --method=sha-512 --stdin') }}"

    - name: Add the user 'Luisre'
      ansible.builtin.user:
        name: Luisre
        group: admin
        password: "{{ lookup('pipe', 'echo -n Luisre12345 | mkpasswd --method=sha-512 --stdin') }}"