---
- hosts: red_hat
  remote_user: root
  become: yes
  tasks:

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Update only security-related packages
      ansible.builtin.yum:
        name: '*'
        security: yes
        state: latest



