---
- hosts: red_hat
  remote_user: root
  become: yes
  tasks:

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Update repositories and apply security updates
      ansible.builtin.yum:
        name: "*"
        state: latest
        security: yes
        deltarpm: no

    - name: Install nmon
      ansible.builtin.yum:
        name: nmon
        state: present
