---
- hosts: red_hat
  remote_user: root
  become: yes
  tasks:

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: checking updates
      yum:
        name: '*'
        security: yes
        state: latest

    - name: Install nmon
      ansible.builtin.yum:
        name: nmon
        state: present
